// Mocks generated by Mockito 5.4.6 from annotations
// in jobodia_frontend/test/cv_builder_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:flutter/widgets.dart' as _i9;
import 'package:get/utils.dart' as _i3;
import 'package:get_storage/src/storage_impl.dart' as _i2;
import 'package:get_storage/src/value.dart' as _i4;
import 'package:image_picker/image_picker.dart' as _i10;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMicrotask_0 extends _i1.SmartFake implements _i2.Microtask {
  _FakeMicrotask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetQueue_1 extends _i1.SmartFake implements _i3.GetQueue {
  _FakeGetQueue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueStorage_2<T> extends _i1.SmartFake
    implements _i4.ValueStorage<T> {
  _FakeValueStorage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLostDataResponse_3 extends _i1.SmartFake
    implements _i5.LostDataResponse {
  _FakeLostDataResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStorage extends _i1.Mock implements _i2.GetStorage {
  @override
  _i2.Microtask get microtask =>
      (super.noSuchMethod(
            Invocation.getter(#microtask),
            returnValue: _FakeMicrotask_0(this, Invocation.getter(#microtask)),
            returnValueForMissingStub: _FakeMicrotask_0(
              this,
              Invocation.getter(#microtask),
            ),
          )
          as _i2.Microtask);

  @override
  Map<String, dynamic> get changes =>
      (super.noSuchMethod(
            Invocation.getter(#changes),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.GetQueue get queue =>
      (super.noSuchMethod(
            Invocation.getter(#queue),
            returnValue: _FakeGetQueue_1(this, Invocation.getter(#queue)),
            returnValueForMissingStub: _FakeGetQueue_1(
              this,
              Invocation.getter(#queue),
            ),
          )
          as _i3.GetQueue);

  @override
  _i4.ValueStorage<Map<String, dynamic>> get listenable =>
      (super.noSuchMethod(
            Invocation.getter(#listenable),
            returnValue: _FakeValueStorage_2<Map<String, dynamic>>(
              this,
              Invocation.getter(#listenable),
            ),
            returnValueForMissingStub:
                _FakeValueStorage_2<Map<String, dynamic>>(
                  this,
                  Invocation.getter(#listenable),
                ),
          )
          as _i4.ValueStorage<Map<String, dynamic>>);

  @override
  _i6.Future<bool> get initStorage =>
      (super.noSuchMethod(
            Invocation.getter(#initStorage),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  set queue(_i3.GetQueue? value) => super.noSuchMethod(
    Invocation.setter(#queue, value),
    returnValueForMissingStub: null,
  );

  @override
  set initStorage(_i6.Future<bool>? value) => super.noSuchMethod(
    Invocation.setter(#initStorage, value),
    returnValueForMissingStub: null,
  );

  @override
  T? read<T>(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  T getKeys<T>() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: _i7.dummyValue<T>(
              this,
              Invocation.method(#getKeys, []),
            ),
            returnValueForMissingStub: _i7.dummyValue<T>(
              this,
              Invocation.method(#getKeys, []),
            ),
          )
          as T);

  @override
  T getValues<T>() =>
      (super.noSuchMethod(
            Invocation.method(#getValues, []),
            returnValue: _i7.dummyValue<T>(
              this,
              Invocation.method(#getValues, []),
            ),
            returnValueForMissingStub: _i7.dummyValue<T>(
              this,
              Invocation.method(#getValues, []),
            ),
          )
          as T);

  @override
  bool hasData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasData, [key]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.VoidCallback listen(_i8.VoidCallback? value) =>
      (super.noSuchMethod(
            Invocation.method(#listen, [value]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i8.VoidCallback);

  @override
  _i8.VoidCallback listenKey(String? key, _i9.ValueSetter<dynamic>? callback) =>
      (super.noSuchMethod(
            Invocation.method(#listenKey, [key, callback]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i8.VoidCallback);

  @override
  _i6.Future<void> write(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void writeInMemory(String? key, dynamic value) => super.noSuchMethod(
    Invocation.method(#writeInMemory, [key, value]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> writeIfNull(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#writeIfNull, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> erase() =>
      (super.noSuchMethod(
            Invocation.method(#erase, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> save() =>
      (super.noSuchMethod(
            Invocation.method(#save, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i10.ImagePicker {
  @override
  _i6.Future<_i5.XFile?> pickImage({
    required _i5.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i5.CameraDevice? preferredCameraDevice = _i5.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {
              #source: source,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #preferredCameraDevice: preferredCameraDevice,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i6.Future<_i5.XFile?>.value(),
            returnValueForMissingStub: _i6.Future<_i5.XFile?>.value(),
          )
          as _i6.Future<_i5.XFile?>);

  @override
  _i6.Future<List<_i5.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiImage, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i6.Future<List<_i5.XFile>>.value(<_i5.XFile>[]),
            returnValueForMissingStub: _i6.Future<List<_i5.XFile>>.value(
              <_i5.XFile>[],
            ),
          )
          as _i6.Future<List<_i5.XFile>>);

  @override
  _i6.Future<_i5.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i6.Future<_i5.XFile?>.value(),
            returnValueForMissingStub: _i6.Future<_i5.XFile?>.value(),
          )
          as _i6.Future<_i5.XFile?>);

  @override
  _i6.Future<List<_i5.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i6.Future<List<_i5.XFile>>.value(<_i5.XFile>[]),
            returnValueForMissingStub: _i6.Future<List<_i5.XFile>>.value(
              <_i5.XFile>[],
            ),
          )
          as _i6.Future<List<_i5.XFile>>);

  @override
  _i6.Future<_i5.XFile?> pickVideo({
    required _i5.ImageSource? source,
    _i5.CameraDevice? preferredCameraDevice = _i5.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [], {
              #source: source,
              #preferredCameraDevice: preferredCameraDevice,
              #maxDuration: maxDuration,
            }),
            returnValue: _i6.Future<_i5.XFile?>.value(),
            returnValueForMissingStub: _i6.Future<_i5.XFile?>.value(),
          )
          as _i6.Future<_i5.XFile?>);

  @override
  _i6.Future<List<_i5.XFile>> pickMultiVideo({
    Duration? maxDuration,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiVideo, [], {
              #maxDuration: maxDuration,
              #limit: limit,
            }),
            returnValue: _i6.Future<List<_i5.XFile>>.value(<_i5.XFile>[]),
            returnValueForMissingStub: _i6.Future<List<_i5.XFile>>.value(
              <_i5.XFile>[],
            ),
          )
          as _i6.Future<List<_i5.XFile>>);

  @override
  _i6.Future<_i5.LostDataResponse> retrieveLostData() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveLostData, []),
            returnValue: _i6.Future<_i5.LostDataResponse>.value(
              _FakeLostDataResponse_3(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.LostDataResponse>.value(
              _FakeLostDataResponse_3(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
          )
          as _i6.Future<_i5.LostDataResponse>);

  @override
  bool supportsImageSource(_i5.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageSource, [source]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
